# Generated by Django 3.1.5 on 2021-03-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firebase_id',
            field=models.CharField(default='', max_length=40),
        ),
    ]
