# Generated by Django 3.1.5 on 2021-03-31 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalystProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('analyst_type', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BidSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=150)),
                ('spreadsheet_id', models.CharField(max_length=150, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level1', models.CharField(help_text='Direct vs Indirect', max_length=50)),
                ('level2', models.CharField(help_text='Windstream, IT, Facilities, etc.', max_length=50)),
                ('level3', models.CharField(help_text='Hardware, Office Supplies, Clerical, etc', max_length=50)),
                ('level4', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=200)),
                ('year_founded', models.CharField(default='', max_length=4)),
                ('office_address', models.CharField(default='', max_length=200)),
                ('plant_address', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('headquarters_address', models.CharField(default='', max_length=200)),
                ('company_ownership', models.CharField(default='', max_length=50)),
                ('number_of_employees', models.CharField(default='', max_length=4)),
                ('annual_sales', models.DecimalField(decimal_places=2, default='', max_digits=21)),
                ('supplier_type', models.CharField(default='', max_length=40)),
                ('main_products_services', models.CharField(default='', max_length=1000)),
                ('other_capabilities', models.CharField(default='', max_length=1000)),
                ('company_website', models.CharField(default='', max_length=150)),
                ('contact_person', models.CharField(default='', max_length=150)),
                ('contact_person_position', models.CharField(default='', max_length=100)),
                ('contact_person_phone', models.CharField(default='', max_length=15)),
                ('contact_person_email', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BizEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_description', models.CharField(blank=True, max_length=150)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField()),
                ('biz_event_name', models.CharField(blank=True, max_length=150)),
                ('template_url', models.CharField(blank=True, max_length=200)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('date_edited', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biz_event_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorToBizEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(blank=True, max_length=150, null=True)),
                ('contract_url', models.CharField(blank=True, max_length=200, null=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('biz_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biz_project_to_vendor', to='App.bizevent')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_to_biz_project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.AddField(
            model_name='bidsheet',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidsheet_category', to='App.category'),
        ),
        migrations.AddField(
            model_name='bidsheet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidsheet_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
