# Generated by Django 3.1.5 on 2021-03-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210331_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='level4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
