# Generated by Django 3.1.5 on 2021-03-31 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20210331_0634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidsheet',
            old_name='spreadsheet_id',
            new_name='spreadsheet_url',
        ),
        migrations.RemoveField(
            model_name='bidsheet',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='bidsheet',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='bidsheet',
            name='template_id',
        ),
    ]
