# Generated by Django 3.1.5 on 2021-04-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20210331_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendortobizevent',
            name='date_signed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
