# Generated by Django 3.1.5 on 2021-04-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_vendortobizevent_date_signed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendortobizevent',
            old_name='is_signed',
            new_name='nda_is_signed',
        ),
        migrations.AddField(
            model_name='vendortobizevent',
            name='analyst_assigned_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendortobizevent',
            name='is_participating',
            field=models.BooleanField(default=False),
        ),
    ]
