# Generated by Django 3.1.5 on 2021-04-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_bizevent_drive_folder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendortobizevent',
            name='spreadsheet_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
