# Generated by Django 3.1.5 on 2021-04-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_vendortobizevent_spreadsheet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendortobizevent',
            name='spreadsheet_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
