# Generated by Django 3.1.5 on 2021-04-10 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0011_vendortobizevent_spreadsheet_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='vendortobizevent',
            name='analyst_assigned_vendor',
            field=models.BooleanField(default=False, help_text='True means the vendor can sign the nda, False means cannot proceed or vendor was taken off the list of participants'),
        ),
        migrations.CreateModel(
            name='EventAdminToBizEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_admin_to_biz_event', to=settings.AUTH_USER_MODEL)),
                ('biz_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biz_project_to_event_admin', to='App.bizevent')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyToCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_company', to='App.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_category', to='App.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ClientToUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_user', to='App.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bizevent',
            name='client',
            field=models.ForeignKey(blank=True, null=True,  on_delete=django.db.models.deletion.CASCADE, related_name='client_to_biz_event', to='App.client'),
            preserve_default=False,
        ),
    ]
