# Generated by Django 3.1.5 on 2021-04-10 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20210410_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bizevent',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_to_biz_event', to='App.client'),
        ),
    ]
