# Generated by Django 3.1.5 on 2021-04-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_auto_20210410_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='company',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='qualitative_questionnaire_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
