# Generated by Django 3.1.5 on 2021-04-12 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_auto_20210412_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bizevent',
            name='company',
        ),
        migrations.AddField(
            model_name='bizevent',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_to_biz_event', to='App.client'),
        ),
    ]
